logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
    root: ALL
    
cognito:
  url: ${COGNITO_URL}
  key: ${COGNITO_KEY}
    
spring:
  profiles:
    active: ${DEPLOYMENT_STAGE}
  application:
    name: user-service

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    
user-service:
  ribbon:
    listOfServers: http://localhost:8765/user-service/
    
---
spring:
  profiles: dev    

server:
  port: 8090
  
---
spring:
  profiles: prod

server:
  port: 5000
    
